### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by ualisher1** [dataquestio/solutions#36]
Couple of questions

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("factbook.db")
cursor = conn.cursor()
cursor.execute(q1).fetchall()

The q1 is missing?

Also, you have two q7 queries, and the second q7 is identical to q6.

**Comment by jaypeedevlin** [comment]
@ualisher1 we do not offer support via GitHub issues.   You should use one of our [support channels](https://www.dataquest.io/help/article/yJqIwwQFW9-what-support-do-i-get).
