### ISSUE TITLE
plt.axhspan Mission188Solution.ipynb

### ISSUE THREAD

**Issue by miwojc** [dataquestio/solutions#39]
to display graphs correctly with red colored zone 0.3 - 0.6 the plt.axhspan line needs to be just before plt.show()
![image](https://user-images.githubusercontent.com/32404415/37807050-c36fa5f0-2e19-11e8-9fc3-cd861a3ba6e9.png)

**Comment by miwojc** [comment]
i can see that your code shows correct at your github repo, however when i used in localy using Jupyter it didn't work correctly, see below:
![image](https://user-images.githubusercontent.com/32404415/37807144-4fb28564-2e1a-11e8-981f-087364555e88.png)

**Comment by jaypeedevlin** [comment]
@miwojc thanks for this - for future reference we don't use github issues as a support channel - you're better to use one of the methods mentioned in this article next time:

https://www.dataquest.io/help/article/yJqIwwQFW9-what-support-do-i-get
