### ISSUE TITLE
Can you tell me the issue with my code?

### ISSUE THREAD

**Issue by Shivam23Thaman** [dataquestio/solutions#68]
`def member_english(a_string):
    for character in a_string:
        if ord(character) > 127:
            return False
        else:
            return True`

`test_app_names = ['Instagram',
                  '爱奇艺PPS -《欢乐颂2》电视剧热播',
                  'Docs To Go™ Free Office Suite',
                   'Instachat 😜']
for app_name in test_app_names:
    eng_or_non_eng = member_english(app_name)
    print(app_name + " is in English : ", eng_or_non_eng)
   `
It is checking just the First Character. what's the difference between putting "Return True" inside the loop with else statement and outside the loop, If I put it outside, It works fine . I'm getting  a little confused here.

**Comment by rhaz96** [comment]
the ```return``` statement halts the code execution.  The moment it encounters a variable whose ```old``` is greater than 127 it the function should return ```False```, which is why ```False``` is on the inside. Only if all characters meet the condition should the function return ```True```, which is why the ```return True``` statement is on the outside.

**Comment by Shivam23Thaman** [comment]
Thank You!
