### ISSUE TITLE
Missing 469

### ISSUE THREAD

**Issue by minhtd1981** [dataquestio/solutions#99]
Hi,

I could not find the guided project for https://app.dataquest.io/m/469/guided-project%3A-popular-data-science-questions/2/stack-exchange

https://github.com/dataquestio/solutions/blob/master/Mission469Solutions.ipynb is not found

Thanks,

**Comment by bmgdc** [comment]
@minhtd1981 Sorry about that. I've fixed it now. Thanks for bringing this to our attention.
